CREATE TABLE `liability_statement` (
`seq_no`  int(11) NOT NULL AUTO_INCREMENT ,
`stock_id`  char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`statement_date`  date NOT NULL ,
`unit`  char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`current_asset`   double NULL DEFAULT NULL ,
`monetary_fund`   double NULL DEFAULT NULL ,
`settlement_fund`  double NULL DEFAULT NULL ,
`lending_fund`  double NULL DEFAULT NULL ,
`trading_financial_asset` double NULL DEFAULT NULL ,
`derivative_financial_asset`  double NULL DEFAULT NULL ,
`note_receivable`  double NULL DEFAULT NULL ,
`account_receivable`  double NULL DEFAULT NULL ,
`advance_payment`  double NULL DEFAULT NULL ,
`premium_receivable`  double NULL DEFAULT NULL ,
`reinsurance_account_receivable`  double NULL DEFAULT NULL ,
`provision_cession_receivable`  double NULL DEFAULT NULL ,
`interest_receivable`  double NULL DEFAULT NULL ,
`dividend_receivable`  double NULL DEFAULT NULL ,
`other_receivable`  double NULL DEFAULT NULL ,
`export_drawback_receivable`  double NULL DEFAULT NULL ,
`allowance_receivable`  double NULL DEFAULT NULL ,
`margin_receivable`  double NULL DEFAULT NULL ,
`internal_receivable`  double NULL DEFAULT NULL ,
`redemptory_monetary_capital`  double NULL DEFAULT NULL ,
`inventory`  double NULL DEFAULT NULL ,
`unamortized_expense`  double NULL DEFAULT NULL ,
`unsettled_current_gl`  double NULL DEFAULT NULL ,
`noncurrent_asset_ayear`  double NULL DEFAULT NULL ,
`other_current_asset`  double NULL DEFAULT NULL ,
`total_current_asset`  double NULL DEFAULT NULL ,
`noncurrent_asset`  double NULL DEFAULT NULL ,
`loans_and_advances`  double NULL DEFAULT NULL ,
`salable_finanical_asset`  double NULL DEFAULT NULL ,
`heldtomaturity_investment`  double NULL DEFAULT NULL ,
`long_term_receivable`  double NULL DEFAULT NULL ,
`longterm_equity_investment`  double NULL DEFAULT NULL ,
`other_longterm_investment`  double NULL DEFAULT NULL ,
`investment_property`  double NULL DEFAULT NULL ,
`original_value_fixed_asset`  double NULL DEFAULT NULL ,
`accumulated_depreciation`  double NULL DEFAULT NULL ,
`net_value_fixed_asset`  double NULL DEFAULT NULL ,
`fixed_asset_depreciation_reserve`  double NULL DEFAULT NULL ,
`net_fixed_asset`  double NULL DEFAULT NULL ,
`construction_in_process`  double NULL DEFAULT NULL ,
`construction_material`  double NULL DEFAULT NULL ,
`fixed_asset_liquidation`  double NULL DEFAULT NULL ,
`productive_biological_asset`  double NULL DEFAULT NULL ,
`welfare_biological_asset`  double NULL DEFAULT NULL ,
`oil_gas_asset`  double NULL DEFAULT NULL ,
`intangible_asset`  double NULL DEFAULT NULL ,
`development_expenditure`  double NULL DEFAULT NULL ,
`goodwill`  double NULL DEFAULT NULL ,
`longterm_deferred_expenditure`  double NULL DEFAULT NULL ,
`circulation_right_equity_separation`  double NULL DEFAULT NULL ,
`deferred_tax_asset`  double NULL DEFAULT NULL ,
`other_noncurrent_asset`  double NULL DEFAULT NULL ,
`total_noncurrent_asset`  double NULL DEFAULT NULL ,
`total_asset`  double NULL DEFAULT NULL ,
`current_liability`  double NULL DEFAULT NULL ,
`short_loan`  double NULL DEFAULT NULL ,
`central_bank_loan`  double NULL DEFAULT NULL ,
`customers_interbank_deposit`  double NULL DEFAULT NULL ,
`borrowing_fund`  double NULL DEFAULT NULL ,
`transaction_financial_liability`  double NULL DEFAULT NULL ,
`derivative_financial_liability`  double NULL DEFAULT NULL ,
`note_payable`  double NULL DEFAULT NULL ,
`account_payable`  double NULL DEFAULT NULL ,
`advance_receipt`  double NULL DEFAULT NULL ,
`financial_asset_sold_repurchase`  double NULL DEFAULT NULL ,
`fee_commission_payable`  double NULL DEFAULT NULL ,
`employee_pay_payable`  double NULL DEFAULT NULL ,
`tax_payable`  double NULL DEFAULT NULL ,
`interest_payable`  double NULL DEFAULT NULL ,
`dividend_payable`  double NULL DEFAULT NULL ,
`other_fee_payable`  double NULL DEFAULT NULL ,
`margin_requirement`  double NULL DEFAULT NULL ,
`internal_account_receivable`  double NULL DEFAULT NULL ,
`other_payable`  double NULL DEFAULT NULL ,
`accrued_expense`  double NULL DEFAULT NULL ,
`expected_current_liability`  double NULL DEFAULT NULL ,
`reinsurance_payable`  double NULL DEFAULT NULL ,
`insurance_contract_provision`  double NULL DEFAULT NULL ,
`acting_trading_security`  double NULL DEFAULT NULL ,
`acting_underwriting_security`  double NULL DEFAULT NULL ,
`international_ticket_settlement`  double NULL DEFAULT NULL ,
`domestic_ticket_settlement`  double NULL DEFAULT NULL ,
`deferred_income`  double NULL DEFAULT NULL ,
`short_term_bond`  double NULL DEFAULT NULL ,
`noncurrent_liability_ayear`  double NULL DEFAULT NULL ,
`other_current_liability`  double NULL DEFAULT NULL ,
`total_current_liability`  double NULL DEFAULT NULL ,
`noncurrent_liability`  double NULL DEFAULT NULL ,
`long_term_loan`  double NULL DEFAULT NULL ,
`bond_payable`  double NULL DEFAULT NULL ,
`long_term_payable`  double NULL DEFAULT NULL ,
`special_payable`  double NULL DEFAULT NULL ,
`expect_noncurrent_liability`  double NULL DEFAULT NULL ,
`deferred_tax_liability`  double NULL DEFAULT NULL ,
`other_noncurrent_liability`  double NULL DEFAULT NULL ,
`total_noncurrent_liability`  double NULL DEFAULT NULL ,
`total_liability`  double NULL DEFAULT NULL ,
`ownership`  double NULL DEFAULT NULL ,
`paid_up_capital`  double NULL DEFAULT NULL ,
`capital_reserve`  double NULL DEFAULT NULL ,
`treasury_stock`  double NULL DEFAULT NULL ,
`special_reserve`  double NULL DEFAULT NULL ,
`surplus_reserve`  double NULL DEFAULT NULL ,
`ordinary_risk_reserve`  double NULL DEFAULT NULL ,
`uncertain_investment_loss`  double NULL DEFAULT NULL ,
`undistributed_profit`  double NULL DEFAULT NULL ,
`distribution_cash_dividend`  double NULL DEFAULT NULL ,
`translation_reserve`  double NULL DEFAULT NULL ,
`total_equity_attributable_parent`  double NULL DEFAULT NULL ,
`minority_equity`  double NULL DEFAULT NULL ,
`total_owners_equity`  double NULL DEFAULT NULL ,
`liability_total_owners_equity`  double NULL DEFAULT NULL ,
PRIMARY KEY (`seq_no`)
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=1
CHECKSUM=0
ROW_FORMAT=FIXED
DELAY_KEY_WRITE=0
;

CREATE TABLE `liability_statement_bank` (
`seq_no`  int(11) NOT NULL AUTO_INCREMENT ,
`stock_id`  char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`statement_date`  date NOT NULL ,
`unit`  char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`asset`  double NULL DEFAULT NULL ,
`monetary_fund`  double NULL DEFAULT NULL ,
`among1`  double NULL DEFAULT NULL ,
`storage_central_bank`  double NULL DEFAULT NULL ,
`balance_deposit`  double NULL DEFAULT NULL ,
`precious_metal`  double NULL DEFAULT NULL ,
`interbank_deposit`  double NULL DEFAULT NULL ,
`lending_fund`  double NULL DEFAULT NULL ,
`inter_lending`  double NULL DEFAULT NULL ,
`interbank_financial_corporation`  double NULL DEFAULT NULL ,
`loan_fellow_bank`  double NULL DEFAULT NULL ,
`note_issuing_fund`  double NULL DEFAULT NULL ,
`derivative_financial_asset`  double NULL DEFAULT NULL ,
`trading_financial_asset`  double NULL DEFAULT NULL ,
`redemptory_monetary_capital`  double NULL DEFAULT NULL ,
`discount`  double NULL DEFAULT NULL ,
`bill_purchased`  double NULL DEFAULT NULL ,
`account_receivable`  double NULL DEFAULT NULL ,
`advance_payment`  double NULL DEFAULT NULL ,
`interest_receivable`  double NULL DEFAULT NULL ,
`loans_and_advances`  double NULL DEFAULT NULL ,
`loan_loss_reserve`  double NULL DEFAULT NULL ,
`capital_vicarious_business`  double NULL DEFAULT NULL ,
`salable_finanical_asset`  double NULL DEFAULT NULL ,
`heldtomaturity_investment`  double NULL DEFAULT NULL ,
`other_receivable`  double NULL DEFAULT NULL ,
`long_term_receivable`  double NULL DEFAULT NULL ,
`longterm_equity_investment`  double NULL DEFAULT NULL ,
`investment_subsidiary`  double NULL DEFAULT NULL ,
`investment_property`  double NULL DEFAULT NULL ,
`investment_fund_receivable`  double NULL DEFAULT NULL ,
`deferred_expense`  double NULL DEFAULT NULL ,
`net_value_fixed_asset`  double NULL DEFAULT NULL ,
`construction_in_process`  double NULL DEFAULT NULL ,
`fixed_asset_liquidation`  double NULL DEFAULT NULL ,
`intangible_asset`  double NULL DEFAULT NULL ,
`goodwill`  double NULL DEFAULT NULL ,
`longterm_deferred_expenditure`  double NULL DEFAULT NULL ,
`pending_insolvent_asset`  double NULL DEFAULT NULL ,
`insolvent_asset_depreciation_reserve`  double NULL DEFAULT NULL ,
`net_pending_insolvent_asset`  double NULL DEFAULT NULL ,
`deferred_tax_asset`  double NULL DEFAULT NULL ,
`bad_loss_special_preparation`  double NULL DEFAULT NULL ,
`other_asset`  double NULL DEFAULT NULL ,
`total_asset`  double NULL DEFAULT NULL ,
`liability`  double NULL DEFAULT NULL ,
`money_debt`  double NULL DEFAULT NULL ,
`loan_central_bank`  double NULL DEFAULT NULL ,
`interbank_deposit_borrowing`  double NULL DEFAULT NULL ,
`interbank_deposit2`  double NULL DEFAULT NULL ,
`borrowing_money`  double NULL DEFAULT NULL ,
`loan_fellow_bank2`  double NULL DEFAULT NULL ,
`foreign_government_loan`  double NULL DEFAULT NULL ,
`derivative_financial_liability`  double NULL DEFAULT NULL ,
`transaction_financial_liability`  double NULL DEFAULT NULL ,
`financial_asset_sold_repurchase`  double NULL DEFAULT NULL ,
`customer_deposit`  double NULL DEFAULT NULL ,
`bill_financing`  double NULL DEFAULT NULL ,
`remittance_temporary_deposit`  double NULL DEFAULT NULL ,
`accrued_expense`  double NULL DEFAULT NULL ,
`issuance_certificate_deposit`  double NULL DEFAULT NULL ,
`outward_remittance`  double NULL DEFAULT NULL ,
`among2`  double NULL DEFAULT NULL ,
`welfare_payable`  double NULL DEFAULT NULL ,
`tax_payable`  double NULL DEFAULT NULL ,
`interest_payable`  double NULL DEFAULT NULL ,
`account_payable`  double NULL DEFAULT NULL ,
`special_payable`  double NULL DEFAULT NULL ,
`dividend_payable`  double NULL DEFAULT NULL ,
`other_fee_payable`  double NULL DEFAULT NULL ,
`liability_vicarious_business`  double NULL DEFAULT NULL ,
`expected_liability`  double NULL DEFAULT NULL ,
`deferred_income`  double NULL DEFAULT NULL ,
`long_term_payable`  double NULL DEFAULT NULL ,
`bond_payable`  double NULL DEFAULT NULL ,
`subprime_bond_payable`  double NULL DEFAULT NULL ,
`deferred_tax_liability`  double NULL DEFAULT NULL ,
`other_liability`  double NULL DEFAULT NULL ,
`total_liability`  double NULL DEFAULT NULL ,
`ownership`  double NULL DEFAULT NULL ,
`paid_up_capital`  double NULL DEFAULT NULL ,
`capital_reserve`  double NULL DEFAULT NULL ,
`salable_investment unrealized_gl`  double NULL DEFAULT NULL ,
`heldtomaturity_investment_gl`  double NULL DEFAULT NULL ,
`treasury_stock`  double NULL DEFAULT NULL ,
`surplus_reserve`  double NULL DEFAULT NULL ,
`ordinary_risk_reserve`  double NULL DEFAULT NULL ,
`trust_compensation_reserve`  double NULL DEFAULT NULL ,
`undistributed_profit`  double NULL DEFAULT NULL ,
`distribution_cash_dividend`  double NULL DEFAULT NULL ,
`translation_reserve`  double NULL DEFAULT NULL ,
`other_reserve`  double NULL DEFAULT NULL ,
`total_equity_attributable_parent`  double NULL DEFAULT NULL ,
`minority_equity`  double NULL DEFAULT NULL ,
`total_owners_equity`  double NULL DEFAULT NULL ,
`liability_total_owners_equity`  double NULL DEFAULT NULL ,
PRIMARY KEY (`seq_no`)
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=1
CHECKSUM=0
ROW_FORMAT=FIXED
DELAY_KEY_WRITE=0
;