CREATE TABLE `profit_statement` (
`seq_no`  int(11) NOT NULL AUTO_INCREMENT ,
`stock_id`  char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`statement_date`  date NOT NULL ,
`unit`  char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`gross_revenue`  double NULL DEFAULT NULL ,
`operating_revenue`  double NULL DEFAULT NULL ,
`interest_income`  double NULL DEFAULT NULL ,
`earned_premium`  double NULL DEFAULT NULL ,
`fee_commission_income`  double NULL DEFAULT NULL ,
`real_estate_income`  double NULL DEFAULT NULL ,
`other_business_income`  double NULL DEFAULT NULL ,
`total_operating_cost`  double NULL DEFAULT NULL ,
`operating_cost`  double NULL DEFAULT NULL ,
`interest_expense`  double NULL DEFAULT NULL ,
`fee_commission_expense`  double NULL DEFAULT NULL ,
`real_estate_cost`  double NULL DEFAULT NULL ,
`research_development_expenditure`  double NULL DEFAULT NULL ,
`surrender_value`  double NULL DEFAULT NULL ,
`net_payments_insurance_claim`  double NULL DEFAULT NULL ,
`insurance_contract_net_reserve`  double NULL DEFAULT NULL ,
`bond_insurance_expense`  double NULL DEFAULT NULL ,
`reinsurance_expense`  double NULL DEFAULT NULL ,
`other_operating_cost`  double NULL DEFAULT NULL ,
`business_tariff_annex`  double NULL DEFAULT NULL ,
`selling_expense`  double NULL DEFAULT NULL ,
`administration_expense`  double NULL DEFAULT NULL ,
`financial_expense`  double NULL DEFAULT NULL ,
`asset_impairment_loss`  double NULL DEFAULT NULL ,
`gain_change_fair_value`  double NULL DEFAULT NULL ,
`investment_income`  double NULL DEFAULT NULL ,
`joint_venture_investment_income`  double NULL DEFAULT NULL ,
`exchange_gain`  double NULL DEFAULT NULL ,
`futures_profit_loss`  double NULL DEFAULT NULL ,
`managed_earning`  double NULL DEFAULT NULL ,
`subsidize_revenue`  double NULL DEFAULT NULL ,
`income_other_operation`  double NULL DEFAULT NULL ,
`operating_profit`  double NULL DEFAULT NULL ,
`nonoperating_income`  double NULL DEFAULT NULL ,
`nonoperating_expenditure`  double NULL DEFAULT NULL ,
`disposal_loss_noncurrent_liability`  double NULL DEFAULT NULL ,
`total_profit`  double NULL DEFAULT NULL ,
`income_tax_expense`  double NULL DEFAULT NULL ,
`unrealised_investment_loss`  double NULL DEFAULT NULL ,
`net_profit`  double NULL DEFAULT NULL ,
`net_profit_parent`  double NULL DEFAULT NULL ,
`minority_interest_income`  double NULL DEFAULT NULL ,
`earning_per_share`  double NULL DEFAULT NULL ,
`basic_earning_per_share`  double NULL DEFAULT NULL ,
`diluted_earning_per_share`  double NULL DEFAULT NULL ,
`other_comprehensive_income`  double NULL DEFAULT NULL ,
`total_comprehensive_income`  double NULL DEFAULT NULL ,
`total_comprehensive_income_parent`  double NULL DEFAULT NULL ,
`total_comprehensive_income_minority`  double NULL DEFAULT NULL ,
PRIMARY KEY (`seq_no`)
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=1
CHECKSUM=0
ROW_FORMAT=FIXED
DELAY_KEY_WRITE=0
;

CREATE TABLE `profit_statement_bank` (
`seq_no`  int(11) NOT NULL AUTO_INCREMENT ,
`stock_id`  char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`statement_date`  date NOT NULL ,
`unit`  char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`operating_revenue`  double NULL DEFAULT NULL ,
`net_interest_income`  double NULL DEFAULT NULL ,
`interest_income`  double NULL DEFAULT NULL ,
`interest_expense`  double NULL DEFAULT NULL ,
`fee_commission_net_income`  double NULL DEFAULT NULL ,
`fee_commission_income`  double NULL DEFAULT NULL ,
`fee_commission_expense`  double NULL DEFAULT NULL ,
`intermediate_business_net_income`  double NULL DEFAULT NULL ,
`intermediate_business_income`  double NULL DEFAULT NULL ,
`intermediate_business_expense`  double NULL DEFAULT NULL ,
`net_trading_income`  double NULL DEFAULT NULL ,
`derivatives_trading_net_income`  double NULL DEFAULT NULL ,
`exchange_gain`  double NULL DEFAULT NULL ,
`net_investment_income`  double NULL DEFAULT NULL ,
`associated_company_investment_income`  double NULL DEFAULT NULL ,
`gain_change_fair_value`  double NULL DEFAULT NULL ,
`income_other_operation`  double NULL DEFAULT NULL ,
`operating_expense`  double NULL DEFAULT NULL ,
`business_tariff_annex`  double NULL DEFAULT NULL ,
`business_administration_expense`  double NULL DEFAULT NULL ,
`asset_impairment_loss`  double NULL DEFAULT NULL ,
`depreciation_expense`  double NULL DEFAULT NULL ,
`provision_doubtful_debt`  double NULL DEFAULT NULL ,
`other_operating_cost`  double NULL DEFAULT NULL ,
`operating_profit`  double NULL DEFAULT NULL ,
`nonoperating_income`  double NULL DEFAULT NULL ,
`nonoperating_expenditure`  double NULL DEFAULT NULL ,
`total_profit`  double NULL DEFAULT NULL ,
`income_tax`  double NULL DEFAULT NULL ,
`minority_interest`  double NULL DEFAULT NULL ,
`net_profit_parent`  double NULL DEFAULT NULL ,
`beginning_retained_earning`  double NULL DEFAULT NULL ,
`profit_available_distribution`  double NULL DEFAULT NULL ,
`withdrawal_legal_surplus`  double NULL DEFAULT NULL ,
`withdraw_statutory_welfare_reserve`  double NULL DEFAULT NULL ,
`allotting_ordinary_risk_reserve`  double NULL DEFAULT NULL ,
`allotting_trust_compensation_reserve`  double NULL DEFAULT NULL ,
`distribution_profit_shareholder`  double NULL DEFAULT NULL ,
`preferred_stock_dividend_payable`  double NULL DEFAULT NULL ,
`withdrawal_other_common_accumulation`  double NULL DEFAULT NULL ,
`common_stock_dividend_payable`  double NULL DEFAULT NULL ,
`dividend_transferred_capital`  double NULL DEFAULT NULL ,
`undistributed_profit`  double NULL DEFAULT NULL ,
`basic_earning_per_share`  double NULL DEFAULT NULL ,
`diluted_earning_per_share`  double NULL DEFAULT NULL ,
PRIMARY KEY (`seq_no`)
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=1
CHECKSUM=0
ROW_FORMAT=FIXED
DELAY_KEY_WRITE=0
;